account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('', views.account, name='account'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('signin/', views.user_login, name='signin'),
    path('signout/', views.user_logout, name='signout'),
    path('dashboard/', views.dashboard, name='dashboard'),

    path('list/', views.ProfileListView.as_view(), name='list'),

    path('user/<int:pk>/update/', views.UserUpdateView.as_view(), name='update'),
    path('profile/<int:pk>/update/', views.ProfileUpdateView.as_view(), name='profile_update'),

    path('staff/user/signup/', views.StaffUserSignUpView.as_view(), name='staff_user_signup'),
    path('staff/user/<int:pk>/update/', views.StaffUserUpdateView.as_view(), name='staff_user_update'),
    path('staff/profile/<int:pk>/update/', views.StaffProfileUpdateView.as_view(), name='staff_profile_update'),
    path('staff/user/<int:pk>/delete/', views.StaffUserDeleteView.as_view(), name='staff_user_delete')
]

events/urls.py
from django.urls import path
from . import views


app_name = "events"
urlpatterns = [
    path('list/', views.EventListView.as_view(), name='list'),
    path('calendar/', views.EventCalendarView.as_view(), name='calendar'),
    path('add/', views.EventCreateView.as_view(), name='create'),
    path('<int:pk>/', views.EventDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', views.EventUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.EventDeleteView.as_view(), name='delete'),
]

sporthub/urls.py
from _curses_panel import panel

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    #path('forgot-password/', views.forgot_password, name='forgot-password'),
    path('account/', include('account.urls', namespace='account')),
    path('events/', include('events.urls', namespace='events')),

    path('settings/', views.settings, name='settings'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

account/views/other.py
from django.views.generic.list import ListView
from ..models import Profile


class ProfileListView(ListView):
    model = Profile
    template_name = "other/profile_list.html"
    ordering = ['user__last_name', 'user__first_name']
    paginate_by = 10

    def get_queryset(self):
        return super().get_queryset().exclude(profileType=4) #exclude Couch

    def get_context_data(self):
        context = super(ProfileListView, self).get_context_data()
        return context

templates/other/profile_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Club{% endblock title %}
{% block activeaccountlist %} active {% endblock activeaccountlist %}
{% block content %}
<div class="container-fluid">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title text-uppercase mb-0">Dojo Residents</h5>
        </div>
        <div class="table-responsive">
            <table class="table no-wrap user-table mb-0">
                <thead>
                <tr>
                    <th scope="col" class="border-0 text-uppercase font-medium pl-4">#</th>
                    <th scope="col" class="border-0"></th>
                    <th scope="col" class="border-0 text-uppercase font-medium">Name</th>
                    <th scope="col" class="border-0 text-uppercase font-medium">Date of Birth</th>
                    <th scope="col" class="border-0 text-uppercase font-medium">Gender</th>
                    <th scope="col" class="border-0 text-uppercase font-medium">Degree</th>
                    <th scope="col" class="border-0 text-uppercase font-medium">Status</th>
                    {% if user.is_staff %}
                        <th scope="col" class="border-0 text-uppercase font-medium">Permissions</th>
                    {% endif %}
                    {% if user.is_staff %}
                        <th scope="col" class="border-0 text-uppercase font-medium">Manage</th>
                    {% endif %}
                </tr>
                </thead>
                <tbody>
                {% for profile in object_list %}
                <tr>
                    <td class="pl-4">{{ forloop.counter }}</td>
                    <td>
                        {% if profile.photo.url is not null %}
                            <img class="rounded-circle me-2" width="30" height="30" src="{{ profile.photo.url }}">
                        {% else %}
                            <img class="rounded-circle me-2" width="30" height="30" src="{%static "img/avatars/nophoto.jpeg" %}">
                        {% endif %}
                    </td>
                    <td>
                        <h5 class="font-medium mb-0">{{profile.fullname}}</h5>
                        <span class="text-muted">{{profile.username}}</span>
                    </td>
                    <td>
                        <span class="text-muted">{{profile.date_of_birth}}</span><br>
                        <span class="text-muted">Age : {{profile.age}}</span>
                    </td>
                    <td>
                        <span class="text-muted">{{profile.gender}}</span><br>
                    </td>
                    <td>
                        <span class="text-muted">{{profile.degree}}</span><br>
                    </td>
                    <td>
                        {% for status in profile.profileType.all %}
                            <span class="text-muted">{{status}}</span><br>
                        {% endfor %}
                    </td>
                    {% if user.is_staff %}
                        <td>
                            {% for group in profile.user.groups.all %}
                                <span class="text-muted">{{group}}</span><br>
                            {% endfor %}
                        </td>
                    {% endif %}
                    {% if user.is_staff %}
                        <td>
                            {% if perms.auth.change_user %}
                                <a href="{% url 'account:staff_user_update' profile.user.id %}">
                                    <button type="button" class="btn btn-outline-success btn-circle btn-lg btn-circle">
                                        <i class="fa fa-edit"></i>
                                    </button>
                                </a>
                            {% endif %}
                            {% if perms.auth.delete_user %}
                                <a href="{% url 'account:staff_user_delete' profile.user.id %}">
                                    <button type="button" class="btn btn-outline-danger btn-circle btn-lg btn-circle ml-2">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                </a>
                            {% endif %}
                            <button type="button" class="btn btn-outline-primary btn-circle btn-lg btn-circle ml-2">
                                <i class="fa fa-download"></i>
                            </button>
                        </td>
                    {% endif %}
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <br>
    <div class="row">
        {% if perms.auth.add_user %}
        <a href="{% url 'account:staff_user_signup' %}">
            <button type="button" class="btn btn-outline-success btn-circle btn-lg btn-circle">
                <i class="fa fa-plus"></i>
            </button>
        </a>
        {% endif %}
    </div>
    {% include "include/paginator_include.html" with page=page %}
</div> 
{% endblock content %}