events/urls.py
from django.urls import path
from . import views


app_name = "events"
urlpatterns = [
    path('list/', views.EventListView.as_view(), name='list'),
    path('calendar/', views.EventCalendarView.as_view(), name='calendar'),
    path('add/', views.EventCreateView.as_view(), name='create'),
    path('<int:pk>/', views.EventDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', views.EventUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.EventDeleteView.as_view(), name='delete'),
]

sporthub/urls.py
from _curses_panel import panel

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    #path('forgot-password/', views.forgot_password, name='forgot-password'),
    path('account/', include('account.urls', namespace='account')),
    path('events/', include('events.urls', namespace='events')),

    path('settings/', views.settings, name='settings'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

account/models.py
from django.db import models
from datetime import date
from django.conf import settings
from phonenumber_field.modelfields import PhoneNumberField


class ProfileType(models.Model):
    typeName = models.CharField(max_length=15, blank=False, null=False, verbose_name='Profile Type')

    def __str__(self):
        return self.typeName


class Profile(models.Model):
    GENDER_CHOICES = (
        (u"M", u"Male"),
        (u"F", u"Female"),
    )
    DEGREE_CHOICES = (
        (u"Mukyu", u"White belt "),
        (u"10th Kyu", u"10 Kyu - Orange belt"),
        (u"9th Kyu", u"9th Kyu – Orange belt with blue stripe"),
        (u"8th Kyu", u"8th Kyu - Blue belt"),
        (u"7th Kyu", u"7th Kyu – Blue belt with green stripe"),
        (u"6th Kyu", u"6th Kyu – Yellow belt"),
        (u"5th Kyu", u"5th Kyu – Yellow belt with orange stripe"),
        (u"4th Kyu", u"4th Kyu – Green belt"),
        (u"3rd Kyu", u"3rd Kyu – Green belt with brown stripe"),
        (u"2nd Kyu", u"2nd Kyu – Brown belt"),
        (u"1st Kyu", u"1st Kyu – Brown belt with black stripe"),
        (u"1st Dan (Shodan)", u"1st Dan - The black belt has one gold stripe"),
        (u"1st Dan (Nidan)", u"2nd Dan – The black belt has two gold stripes"),
        (u"1st Dan (Sandan)", u"3rd Dan – The black belt has three gold stripes"),
        (u"1st Dan (Yondan)", u"4th Dan – The black belt has four gold stripes"),
        (u"1st Dan (Godan)", u"5th Dan - The black belt has five gold stripes"),
        (u"1st Dan (Rokudan)", u"6th Dan – The black belt has six gold stripes"),
        (u"1st Dan (Shichidan)", u"7th Dan – The black belt has seven gold stripes"),
        (u"1st Dan (Hachidan)", u"8th Dan – The black belt has eight gold stripes"),
        (u"1st Dan (Kyūdan)", u"9th Dan – The black belt has nine gold stripes"),
        (u"1st Dan (Jūdan)", u"10th Dan – The black belt has ten gold stripes")
    )
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    country = models.CharField(max_length=50, blank=True, null=True)
    city = models.CharField(max_length=50, blank=True, null=True)
    address = models.CharField(max_length=100, blank=True, null=True)
    gender = models.CharField(max_length=2, choices=GENDER_CHOICES, blank=True, null=True)
    phone = PhoneNumberField(blank=True, null=True, unique=True)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='media/users/avatars/%Y/%m/%d', blank=True)
    degree = models.CharField(max_length=20, choices=DEGREE_CHOICES, blank=True, null=True)
    profileType = models.ManyToManyField(ProfileType)

    def __str__(self):
        return 'Profile for user {}'.format(self.user.username)

    def fullname(self):
        return '{} {}'.format(self.user.last_name, self.user.first_name)

    def username(self):
        return self.user.username

    def age(self):
        today = date.today()
        if self.date_of_birth:
            return today.year - self.date_of_birth.year - ((today.month, today.day) < (self.date_of_birth.month, self.date_of_birth.day))

account/forms/staff.py
import datetime
from django import forms
from django.contrib.auth.models import User, Group, Permission
from ..models import Profile, ProfileType


class StaffUserSignUpForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control form-control-user', 'type': 'password', 'name': 'password', 'placeholder': 'Password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control form-control-user', 'type': 'password', 'name': 'password2', 'placeholder': 'Repeat Password'}))
    group = forms.ModelChoiceField(queryset=Group.objects.all(), required=False)
    is_active = forms.BooleanField(required=False)
    is_staff = forms.BooleanField(required=False)
    is_superuser = forms.BooleanField(required=False)
    date_joined = forms.DateField(initial=datetime.date.today, required=False, widget=forms.DateInput(format=('%Y-%m-%d'), attrs={'class': 'form-control form-control-user', 'type': 'hidden', 'placeholder': 'Select a Date of Registration', 'name': 'date_joined'}))

    class Meta:
        model = User
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(StaffUserSignUpForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-control form-control-user', 'type': 'text', 'name': 'username', 'placeholder': 'User Name'})
        self.fields['email'].widget.attrs.update({'class': 'form-control form-control-user', 'type': 'text', 'aria-describedby': 'emailHelp', 'name': 'email', 'placeholder': 'Email Address'})
        self.fields['first_name'].widget.attrs.update({'class': 'form-control form-control-user', 'type': 'text', 'name': 'first_name', 'placeholder': 'First Name'})
        self.fields['last_name'].widget.attrs.update({'class': 'form-control form-control-user', 'type': 'text', 'name': 'last_name', 'placeholder': 'Last Name'})

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Password don\'t match.')
        return cd['password2']


class StaffUserUpdateForm(forms.ModelForm):
    groups = forms.ModelMultipleChoiceField(queryset=Group.objects.all(), required=False)
    is_active = forms.BooleanField(required=False)
    is_staff = forms.BooleanField(required=False)
    is_superuser = forms.BooleanField(required=False)

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'groups', 'is_active', 'is_staff', 'is_superuser']

    def __init__(self, *args, **kwargs):
        super(StaffUserUpdateForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-control form-control-user', 'type': 'text', 'name': 'username', 'placeholder': 'User Name'})
        self.fields['email'].widget.attrs.update({'class': 'form-control form-control-user', 'type': 'text', 'aria-describedby': 'emailHelp', 'name': 'email', 'placeholder': 'Email Address'})
        self.fields['first_name'].widget.attrs.update({'class': 'form-control form-control-user', 'type': 'text', 'name': 'first_name', 'placeholder': 'First Name'})
        self.fields['last_name'].widget.attrs.update({'class': 'form-control form-control-user', 'type': 'text', 'name': 'last_name', 'placeholder': 'Last Name'})
        self.fields['groups'].empty_label = None


class StaffProfileUpdateForm(forms.ModelForm):
    date_of_birth = forms.DateField(required=False, widget=forms.DateInput(format=('%Y-%m-%d'), attrs={'class': 'form-control form-control-user', 'type': 'date', 'placeholder': 'Select a Date of Birth', 'name': 'date_of_birth'}))

    class Meta:
        model = Profile
        fields = ['country', 'city', 'address', 'gender', 'phone', 'degree', 'profileType', 'date_of_birth', 'photo']

    def __init__(self, *args, **kwargs):
        super(StaffProfileUpdateForm, self).__init__(*args, **kwargs)
        self.fields['country'].widget.attrs.update({'class': 'form-control form-control-user', 'type': 'text', 'name': 'country', 'placeholder': 'Country'})
        self.fields['city'].widget.attrs.update({'class': 'form-control form-control-user', 'type': 'text', 'name': 'city', 'placeholder': 'City'})
        self.fields['address'].widget.attrs.update({'class': 'form-control form-control-user', 'type': 'text', 'name': 'address', 'placeholder': 'Address'})
        self.fields['gender'].widget.attrs.update({'class': 'form-control form-control-user', 'type': 'text', 'name': 'gender', 'placeholder': 'Gender'})
        self.fields['phone'].widget.attrs.update({'class': 'form-control form-control-user', 'type': 'text', 'name': 'phone', 'placeholder': 'Phone number'})
        self.fields['degree'].widget.attrs.update({'class': 'form-control form-control-user', 'type': 'text', 'name': 'degree', 'placeholder': 'Degree'})
        self.fields['gender'].empty_label = None
        self.fields['degree'].empty_label = None
        self.fields['profileType'].empty_label = None

account/views/staff.py
import datetime
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.contrib.auth.models import User, Group, Permission
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from ..forms import StaffUserSignUpForm, StaffUserUpdateForm, StaffProfileUpdateForm
from ..models import Profile


class StaffUserSignUpView(CreateView):
    model = User
    template_name = 'staff/user_signup.html'
    form_class = StaffUserSignUpForm

    def get_context_data(self, **kwargs):
        context = super(StaffUserSignUpView, self).get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        user = form.save()
        profile = Profile.objects.create(user=user)
        user.date_joined = datetime.datetime.now()
        user.is_active = form.cleaned_data['is_active']
        user.is_staff = form.cleaned_data['is_staff']
        user.is_superuser = form.cleaned_data['is_superuser']
        messages.success(self.request, 'User {} {} has been successfully added.'.format(user.first_name, user.last_name))
        return super(StaffUserSignUpView, self).form_valid(form)

    def get_success_url(self):
        if self.request.POST.get('_save'):
            return reverse_lazy('account:list')
        if self.request.POST.get('_addanother'):
            return reverse_lazy('account:staff_user_signup')
        if self.request.POST.get('_continue'):
            return reverse_lazy('account:staff_profile_update', kwargs={'pk': self.object.profile.pk})


class StaffUserUpdateView(UpdateView):
    model = User
    template_name = 'staff/user_update.html'
    form_class = StaffUserUpdateForm
    context_object_name = 'other_user'

    @property
    def has_permission(self):
        return self.user.is_active and self.user.is_staff

    def get_context_data(self, **kwargs):
        context = super(StaffUserUpdateView, self).get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        usr = form.save()
        messages.success(self.request, 'User {} {} has been successfully updated.'.format(usr.first_name, usr.last_name))
        return super(StaffUserUpdateView, self).form_valid(form)

    def get_success_url(self):
        if self.request.POST.get('_save'):
            return reverse_lazy('account:staff_user_update', kwargs={'pk': self.object.pk})
        if self.request.POST.get('_continue'):
            return reverse_lazy('account:staff_profile_update', kwargs={'pk': self.object.profile.pk})


class StaffProfileUpdateView(UpdateView):
    model = Profile
    template_name = 'staff/profile_update.html'
    form_class = StaffProfileUpdateForm
    context_object_name = 'other_profile'

    @property
    def has_permission(self):
        return self.user.is_active and self.user.is_staff

    def get_context_data(self, **kwargs):
        context = super(StaffProfileUpdateView, self).get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        profile = form.save()
        messages.success(self.request, 'Profile for User {} has been successfully updated.'.format(profile.fullname()))
        return super(StaffProfileUpdateView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('account:staff_profile_update', kwargs={'pk': self.object.pk})


class StaffUserDeleteView(DeleteView):
    model = User
    template_name = 'staff/user_confirm_delete.html'
    context_object_name = 'other_user'

    def get_success_url(self):
        return reverse_lazy('account:list')

    def post(self, request, *args, **kwargs):
        if self.request.POST.get('_cancel'):
            url = self.get_success_url()
            return HttpResponseRedirect(url)
        else:
            return super(StaffUserDeleteView, self).post(request, *args, **kwargs)

templates/staff/profile_update.html
{% extends "base.html" %}
{% load static %}

{% block title %}Edit Profile - KarateLog {% endblock title %}
{% block activeaccountlist %} active {% endblock activeaccountlist %}
{% block content %}
    <div class="container-fluid">
        <div class="row mb-3">
            <div class="col-lg-12">
                <div class="row">
                    <div class="col">
                        <div class="card shadow mb-3">
                            <div class="card-header py-3">
                                <p class="text-primary m-0 fw-bold">Edit Profile Settings</p>
                            </div>
                            <div class="card-body shadow">
                                {% if form.errors %}
                                    <div class="alert alert-danger">
                                        {{ form.errors }}
                                    </div>
                                {% endif %}
                                <form class="profile" action="." method="post" enctype="multipart/form-data">
                                    <div class="row">
                                        <div class="text-center">
                                            {% if form.instance.photo %}
                                                <img class="rounded-circle mb-3 mt-4" src="{{ form.instance.photo.url }}" width="160" height="160">
                                            {% else %}
                                                <img class="rounded-circle mb-3 mt-4" src="{%static "img/avatars/nophoto.jpeg" %}">
                                            {% endif %}
                                            <br>
                                            {{ form.photo }}
                                        </div>
                                    </div>
                                    <hr>
                                    <div class="row">
                                        <div class="col">
                                            <div class="mb-3">
                                                <label class="form-label" for="country"><strong>Country</strong></label>
                                                {{ form.country }}
                                            </div>
                                        </div>
                                        <div class="col">
                                            <div class="mb-3">
                                                <label class="form-label" for="city"><strong>City</strong></label>
                                                {{ form.city }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col">
                                            <div class="mb-3">
                                                <label class="form-label" for="address"><strong>Address</strong></label>
                                                {{ form.address }}
                                            </div>
                                        </div>
                                        <div class="col">
                                            <div class="mb-3">
                                                <label class="form-label" for="phone"><strong>Phone Number</strong></label>
                                                {{ form.phone }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col">
                                            <div class="mb-3">
                                                <label class="form-label" for="date_of_birth"><strong>Date of Birth</strong></label>
                                                {{ form.date_of_birth }}
                                            </div>
                                        </div>
                                        <div class="col">
                                            <div class="row">
                                                <div class="col-sm-2 mb-2 mb-sm-0">
                                                    <div class="mb-3">
                                                        <label class="form-label" for="gender"><strong>Gender</strong></label>
                                                        <p>
                                                            <select name="gender" id="id_gender">
                                                                {% for gender in form.gender %}
                                                                    {{ gender  }}
                                                                {% endfor %}
                                                            </select>
                                                        </p>
                                                    </div>
                                                </div>
                                                <div class="col-sm-6 mb-6 mb-sm-0">
                                                    <div class="mb-3">
                                                        <label class="form-label" for="degree"><strong>Degree</strong></label>
                                                        <p>
                                                            <select name="degree" id="id_degree">
                                                                {% for degree in form.degree %}
                                                                    {{ degree  }}
                                                                {% endfor %}
                                                            </select>
                                                        </p>
                                                    </div>
                                                </div>
                                                <div class="col-sm-4 mb-4 mb-sm-0">
                                                    <div class="mb-3">
                                                        <label class="form-label" for="profileType"><strong>Profile Type</strong></label>
                                                        <p>
                                                            <select class="form-control" onfocus='this.size=6;' name="profileType" id="profileType" multiple>
                                                                {% for profileType in form.profileType %}
                                                                    {{ profileType  }}
                                                                {% endfor %}
                                                            </select>
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    {% csrf_token %}
                                    <div class="mb-3 text-center">
                                        <button class="btn btn-primary btn-sm" type="submit">Save Profile</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/staff/user_signup.html
{% extends "base.html" %}
{% load static %}

{% block title %}Add New User - KarateLog {% endblock title %}
{% block activeaccountlist %} active {% endblock activeaccountlist %}
{% block content %}
    <div class="card shadow-lg o-hidden border-0 my-5">
        <div class="card-body p-0">
            <div class="row">
                <div class="col-lg-12">
                    <div class="p-5">
                        <div class="text-center">
                            <h4 class="text-dark mb-4">Create a New Account!</h4>
                        </div>
                        {% if form.errors %}
                            <div class="alert alert-danger">
                                {{ form.errors }}
                            </div>
                        {% endif %}
                        <form class="user" action="." method="post">
                            <p>Account Attributes</p>
                            <div class="row mb-3">
                                <div class="col-sm-6 mb-6 mb-sm-0">
                                    {{ form.username }}
                                </div>
                                <div class="col-sm-6 mb-6 mb-sm-0">
                                    {{ form.email }}
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-sm-6 mb-6 mb-sm-0">
                                    {{ form.first_name }}
                                </div>
                                <div class="col-sm-6 mb-6 mb-sm-0">
                                    {{ form.last_name }}
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-sm-6 mb-3 mb-sm-0">
                                    {{ form.password }}
                                </div>
                                <div class="col-sm-6">
                                    {{ form.password2 }}
                                </div>
                            </div>
                            <hr>
                            <p>Account Permissions</p>
                            <div class="row mb-3">
                                <div class="col-sm-3 mb-3 mb-sm-0">
                                    <label for="groups">Choose a Group:</label>
                                    <select class="form-control" name="groups" id="groups" multiple>
                                        {% for group in form.groups %}
                                            {{ group }}
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="col-sm-3 mb-3 mb-sm-0">
                                    <p>Status:</p>
                                    <p>
                                        {{ form.is_active }}
                                        <label for="id_is_active">Active</label><br>
                                        {{ form.is_staff }}
                                        <label for="id_is_staff">Staff Status</label><br>
                                        {{ form.is_superuser }}
                                        <label for="id_is_superuser">SuperUser Status</label><br>
                                    </p>
                                </div>
                                {{form.date_joined}}
                            </div>
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-sm-4 mb-4 mb-sm-0">
                                    <input class="default btn btn-primary d-block btn-user w-100"  type="submit" value="Save" name="_save">
                                </div>
                                <div class="col-sm-4 mb-4 mb-sm-0">
                                    <input class="btn btn-primary d-block btn-user w-100" type="submit" value="Save and add another" name="_addanother">
                                </div>
                                <div class="col-sm-4 mb-4 mb-sm-0">
                                    <input class="btn btn-primary d-block btn-user w-100" type="submit" value="Save and continue editing" name="_continue">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/staff/user_update.html
{% extends "base.html" %}
{% load static %}

{% block title %}Edit User - KarateLog {% endblock title %}
{% block activeaccountlist %} active {% endblock activeaccountlist %}
{% block content %}
    <div class="container-fluid">
        <div class="row mb-3">
            <div class="col-lg-12">
                <div class="row">
                    <div class="col">
                        <div class="card shadow mb-3">
                            <div class="card-header py-3">
                                <p class="text-primary m-0 fw-bold">Edit User Settings</p>
                            </div>
                            <div class="card-body shadow">
                                {% if form.errors %}
                                    <div class="alert alert-danger">
                                        {{ form.errors }}
                                    </div>
                                {% endif %}
                                <form class="user" action="." method="post">
                                    <div class="row">
                                        <div class="col">
                                            <div class="mb-3">
                                                <label class="form-label" for="username"><strong>Username</strong></label>
                                                {{ form.username }}
                                            </div>
                                        </div>
                                        <div class="col">
                                            <div class="mb-3">
                                                <label class="form-label" for="email"><strong>Email Address</strong></label>
                                                {{ form.email }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col">
                                            <div class="mb-3">
                                                <label class="form-label" for="first_name"><strong>First Name</strong></label>
                                                {{ form.first_name }}
                                            </div>
                                        </div>
                                        <div class="col">
                                            <div class="mb-3">
                                                <label class="form-label" for="last_name"><strong>Last Name</strong></label>
                                                {{ form.last_name }}
                                            </div>
                                        </div>
                                    </div>
                                    <p>Account Permissions</p>
                                    <div class="row mb-3">
                                    <div class="col-sm-3 mb-3 mb-sm-0">
                                        <label for="groups">Choose a Group:</label>
                                        <select class="form-control" name="groups" id="groups" multiple>
                                            {% for group in form.groups %}
                                                {{ group  }}
                                            {% endfor %}
                                        </select>
                                    </div>
                                    <div class="col-sm-3 mb-3 mb-sm-0">
                                        <p>Status:</p>
                                        <p>
                                            {{ form.is_active }}
                                            <label for="id_is_active">Active</label><br>
                                            {{ form.is_staff }}
                                            <label for="id_is_staff">Staff Status</label><br>
                                            {{ form.is_superuser }}
                                            <label for="id_is_superuser">SuperUser Status</label><br>
                                        </p>
                                    </div>
                                    {% csrf_token %}
                                    <div class="row">
                                        <div class="col-sm-3 mb-3 mb-sm-0">
                                        </div>
                                        <div class="col-sm-3 mb-3 mb-sm-0">
                                            <input class="default btn btn-primary d-block btn-user w-100"  type="submit" value="Save" name="_save">
                                        </div>
                                        <div class="col-sm-3 mb-3 mb-sm-0">
                                            <input class="btn btn-primary d-block btn-user w-100" type="submit" value="Save and Edit Profile" name="_continue">
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}