events/urls.py
from django.urls import path
from . import views


app_name = "events"
urlpatterns = [
    path('list/', views.EventListView.as_view(), name='list'),
    path('calendar/', views.EventCalendarView.as_view(), name='calendar'),
    path('add/', views.EventCreateView.as_view(), name='create'),
    path('<int:pk>/', views.EventDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', views.EventUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.EventDeleteView.as_view(), name='delete'),
]

sporthub/urls.py
from _curses_panel import panel

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    #path('forgot-password/', views.forgot_password, name='forgot-password'),
    path('account/', include('account.urls', namespace='account')),
    path('events/', include('events.urls', namespace='events')),

    path('settings/', views.settings, name='settings'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

events/models/event.py
from datetime import datetime
from django.db import models
from django.urls import reverse

from .event_abstract import EventAbstract
from django.contrib.auth.models import User


class EventManager(models.Manager):
    """ Event manager """

    def get_all_events(self):
        events = Event.objects.filter(is_active=True, is_deleted=False)
        return events

    '''def get_active_events(self):
        active_events = Event.objects.filter(is_active=True, is_deleted=False)
        return active_events

    def get_user_events(self, user):
        user_events = Event.objects.filter(user=user, is_active=True, is_deleted=False)
        return user_events

    def get_actual_events(self):
        actual_events = Event.objects.filter(is_active=True, is_deleted=False, subscribe_date__gte=datetime.now().date()).order_by("subscribe_date")
        return actual_events'''


class Event(EventAbstract):
    """ Event model """
    title = models.CharField(max_length=200, unique=True)
    country = models.CharField(max_length=25, default='Ukraine')
    city = models.CharField(max_length=25,default='Kharkiv')
    description = models.TextField()
    start_date = models.DateField()
    end_date = models.DateField()
    subscribe_date = models.DateField()
    notes = models.TextField(blank=True)
    photo = models.ImageField(upload_to='events/img/', blank=True)
    attachment = models.FileField(upload_to='events/att/', blank=True)

    objects = EventManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("events:event-detail", args=(self.id,))

    @property
    def get_html_url(self):
        url = reverse("events:event-detail", args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'

events/models/event_abstract.py
from django.db import models


class EventAbstract(models.Model):
    """ Event abstract model """

    is_active = models.BooleanField(default=True)
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

events/models/event_member.py
from django.db import models

from django.contrib.auth.models import User
from events.models import Event, EventAbstract


'''class EventMember(EventAbstract):
    """ Event member model """

    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name="events")
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="event_members"
    )
    weight = models.DecimalField(max_digits=5, decimal_places=1)

    class Meta:
        unique_together = ["event", "user"]

    def __str__(self):
        return str(self.user)
'''

events/forms.py
from django.forms import ModelForm, DateInput
from .models import Event
from django import forms


class EventCreateForm(forms.ModelForm):
    start_date = forms.DateField(required=True, widget=forms.DateInput(format=('%Y-%m-%d'), attrs={'class': 'form-control form-control-user', 'type': 'date', 'placeholder': 'Select a Date of Start Event', 'name': 'start_date'}))
    end_date = forms.DateField(required=True, widget=forms.DateInput(format=('%Y-%m-%d'), attrs={'class': 'form-control form-control-user', 'type': 'date', 'placeholder': 'Select a Date of End Event', 'name': 'end_date'}))
    subscribe_date = forms.DateField(required=True, widget=forms.DateInput(format=('%Y-%m-%d'), attrs={'class': 'form-control form-control-user', 'type': 'date', 'placeholder': 'Select a Date of Last Subscribe Date', 'name': 'subscribe_date'}))

    class Meta:
        model = Event
        fields = ['title', 'description', 'start_date', 'end_date', 'subscribe_date']

    def __init__(self, *args, **kwargs):
        super(EventCreateForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'form-control form-control-user', 'type': 'text', 'name': 'title', 'placeholder': 'Title'})
        self.fields['description'].widget.attrs.update({'style': 'height: 400px; border-radius: 2rem;', 'class': 'form-control form-control-user', 'type': 'text', 'name': 'description', 'placeholder': 'Description'})


class EventUpdateForm(forms.ModelForm):
    start_date = forms.DateField(required=True, widget=forms.DateInput(format=('%Y-%m-%d'), attrs={'class': 'form-control form-control-user', 'type': 'date', 'placeholder': 'Select a Date of Start Event', 'name': 'start_date'}))
    end_date = forms.DateField(required=True, widget=forms.DateInput(format=('%Y-%m-%d'), attrs={'class': 'form-control form-control-user', 'type': 'date', 'placeholder': 'Select a Date of End Event', 'name': 'end_date'}))
    subscribe_date = forms.DateField(required=True, widget=forms.DateInput(format=('%Y-%m-%d'), attrs={'class': 'form-control form-control-user', 'type': 'date', 'placeholder': 'Select a Date of Last Subscribe Date', 'name': 'subscribe_date'}))

    class Meta:
        model = Event
        fields = ['title', 'description', 'start_date', 'end_date', 'subscribe_date', 'country', 'city', 'notes', 'photo', 'attachment']

    def __init__(self, *args, **kwargs):
        super(EventUpdateForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'form-control form-control-user', 'type': 'text', 'name': 'title', 'placeholder': 'Title'})
        self.fields['description'].widget.attrs.update({'style': 'height: 400px; border-radius: 2rem;', 'class': 'form-control form-control-user', 'type': 'text', 'name': 'description', 'placeholder': 'Description'})
        self.fields['country'].widget.attrs.update({'class': 'form-control form-control-user', 'type': 'text', 'name': 'country', 'placeholder': 'Country'})
        self.fields['city'].widget.attrs.update({'class': 'form-control form-control-user', 'type': 'text', 'name': 'city', 'placeholder': 'City'})
        self.fields['notes'].widget.attrs.update({'style': 'height: 400px; border-radius: 2rem;', 'class': 'form-control form-control-user', 'type': 'text', 'name': 'notes', 'placeholder': 'Notes'})

events/views.py
import os
from django.conf import settings
from django.contrib import messages
from django.urls import reverse, reverse_lazy
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.views.generic import View
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django_downloadview import PathDownloadView
from .forms import EventCreateForm, EventUpdateForm
from .models import Event


app_dir = os.path.dirname(os.path.abspath(__file__))
project_dir = os.path.dirname(app_dir)
fixtures_dir = os.path.join(project_dir, "fixtures")
#: Path to a text file that says 'Hello world!'.
hello_world_path = os.path.join(fixtures_dir, "hello-world.txt")

#: Serve ``fixtures/hello-world.txt`` file.
static_path = PathDownloadView.as_view(path=hello_world_path)

class EventListView(ListView):
    template_name = 'events/list.html'
    model = Event
    paginate_by = 10

    def get_queryset(self):
        return Event.objects.get_all_events()

    def get_context_data(self):
        context = super(EventListView, self).get_context_data()
        context['subscriber'] = {}
        return context


class EventCalendarView(ListView):
    template_name = 'events/calendar.html'
    model = Event

    def get_queryset(self):
        return Event.objects.get_all_events()

    def get_context_data(self):
        context = super(EventCalendarView, self).get_context_data()
        return context


class EventCreateView(CreateView):
    template_name = 'events/create.html'
    model = Event
    form_class = EventCreateForm

    def get_context_data(self, **kwargs):
        context = super(EventCreateView, self).get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        event = form.save()
        messages.success(self.request, 'Event {} has been successfully added.'.format(event.title))
        return super(EventCreateView, self).form_valid(form)

    def get_success_url(self):
        if self.request.POST.get('_save'):
            return reverse_lazy('events:list')
        if self.request.POST.get('_addanother'):
            return reverse_lazy('events:create')


class EventUpdateView(UpdateView):
    template_name = 'events/update.html'
    model = Event
    form_class = EventUpdateForm

    @property
    def has_permission(self):
        return self.user.is_active

    def get_context_data(self, **kwargs):
        context = super(EventUpdateView, self).get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        event = form.save()
        messages.success(self.request, 'Event \"{}\" has been successfully updated.'.format(event.title))
        return super(EventUpdateView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('events:list')


class EventDeleteView(DeleteView):
    model = Event
    template_name = 'events/confirm_delete.html'

    def get_success_url(self):
        return reverse_lazy('events:list')

    def post(self, request, *args, **kwargs):
        if self.request.POST.get('_cancel'):
            url = self.get_success_url()
            return HttpResponseRedirect(url)
        else:
            return super(EventDeleteView, self).post(request, *args, **kwargs)


class EventDetailView(DetailView):
    model = Event
    template_name = 'events/detail.html'

    def get_context_data(self, **kwargs):
        context = super(EventDetailView, self).get_context_data(**kwargs)
        return context


class DownloadAttachmentView(PathDownloadView):
    """Serve file in ``settings.MEDIA_ROOT``.
    .. warning::
       Make sure to prevent "../" in path via URL patterns.
    .. note::
       This particular setup would be easier to perform with
       :class:`StorageDownloadView`
    """

    def get_path(self):
        """Return path inside fixtures directory."""
        # Get path from URL resolvers or as_view kwarg.
        relative_path = super(DownloadAttachmentView, self).get_path()
        # Make it absolute.
        absolute_path = os.path.join(fixtures_dir, relative_path)
        return absolute_path

templates/events/calendar.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Events{% endblock title %}
{% block activeevents %} active {% endblock activeevents %}
{% block content %}
<div class="container-fluid">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title text-uppercase mb-0">Events</h5>
        </div>
        <div class="table-responsive">
            <div id="sampleTable_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">
                <div class="row">
                    <ul class="nav nav-tabs">
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'events:list' %}">List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'events:calendar' %}">Calendar</a>
                        </li>
                    </ul>
                </div>
                <br>
                <div class="row">
                    <div class="col-sm-12">
                        <table class="table table-hover table-bordered dataTable no-footer" id="sampleTable" role="grid" aria-describedby="sampleTable_info">
                            <thead>
                            <tr role="row">
                                <th style="width: 30px;">#</th>
                                <th scope="col" class="border-0 text-uppercase font-medium">Event Name</th>
                                <th scope="col" class="border-0 text-uppercase font-medium">Start Date</th>
                                <th scope="col" class="border-0 text-uppercase font-medium">End Date</th>
                                <th scope="col" class="border-0 text-uppercase font-medium">Subscribe Date</th>
                                {% if user.is_staff %}
                                    <th scope="col" class="border-0 text-uppercase font-medium">Manage</th>
                                {% endif %}
                            </tr>
                            </thead>
                            <tbody>
                            {% for event in object_list %}
                            <tr role="row" class="odd">
                                    <td>{{ forloop.counter }}</td>
                                <a href="{% url 'events:update' event.id %}">
                                    <td>{{ event.title }}</td>
                                </a>
                                    <td>{{ event.start_date }}</td>
                                    <td>{{ event.end_date }}</td>
                                    <td>{{ event.subscribe_date }}</td>
                                {% if user.is_staff %}
                                <td>
                                    {% if user.is_staff %}
                                        {% if perms.auth.change_user %}
                                            <a href="{% url 'events:update' event.id %}">
                                                <button type="button" class="btn btn-outline-success btn-circle btn-lg btn-circle">
                                                    <i class="fa fa-edit"></i>
                                                </button>
                                            </a>
                                        {% endif %}
                                        {% if perms.auth.delete_user %}
                                        <a href="{% url 'events:delete' event.id %}">
                                            <button type="button" class="btn btn-outline-danger btn-circle btn-lg btn-circle ml-2">
                                                <i class="fa fa-trash"></i>
                                            </button>
                                        </a>
                                    {% endif %}
                                        <button type="button" class="btn btn-outline-primary btn-circle btn-lg btn-circle ml-2">
                                            <i class="fa fa-download"></i>
                                        </button>
                                    {% endif %}
                                </td>
                            {% endif %}
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="row">
        {% if perms.auth.add_user %}
        <a href="{% url 'events:create' %}">
            <button type="button" class="btn btn-outline-primary btn-circle btn-lg btn-circle">
                <i class="fa fa-plus"></i>
            </button>
        </a>
        {% endif %}
    </div>
    {% include "include/paginator_include.html" with page=page %}
</div>
{% endblock content %}

templates/events/confirm_delete.html
{% extends "base.html" %}
{% block title %}Delete User - KarateLog {% endblock title %}
{% block activeaccountlist %} active {% endblock activeaccountlist %}
{% block content %}
<div class="card shadow-lg o-hidden border-0 my-5">
	<div class="card-body p-0">
		<div class="row">
			<div class="col-lg-12">
				<div class="p-5">
					<div class="text-center">
						<h4 class="text-dark mb-4">Delete event confirm</h4>
					</div>
					{% if message %}
						<div class="alert alert-success" role="alert">
							{% for message in messages %}
								{{ message }}
							{% endfor %}
						</div>
					{% endif %}
					<form method="post">
						{% csrf_token %}
						<div class="row">
							<div class="col-sm-3 mb-3 mb-sm-0">
							</div>
							<div class="col-sm-3 mb-3 mb-sm-0">
								<input class="default btn btn-primary d-block btn-user w-100"  type="submit" value="Yes, Delete" name="_confirm">
							</div>
							<div class="col-sm-3 mb-3 mb-sm-0">
								<input class="default btn btn-primary d-block btn-user w-100"  type="submit" value="No, Cancel" name="_cancel">
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/events/create.html
{% extends "base.html" %}
{% load static %}

{% block title %}Create New Event {% endblock title %}
{% block activeevents %} active {% endblock activeevents %}
{% block content %}
    <div class="card shadow-lg o-hidden border-0 my-5">
        <div class="card-body p-0">
            <div class="row">
                <div class="col-lg-12">
                    <div class="p-5">
                        <div class="text-center">
                            <h4 class="text-dark mb-4">Create a New Event!</h4>
                        </div>
                        {% if form.errors %}
                            <div class="alert alert-danger">
                                {{ form.errors }}
                            </div>
                        {% endif %}
                        <form class="user" action="." method="post">
                            <div class="row mb-12">
                                <div class="col-sm-6 mb-6 mb-sm-0">
                                    <div class="row">
                                        <div class="col-sm-12 mb-12 mb-sm-0">
                                            {{ form.title }}
                                        </div>
                                    </div>
                                    <br>
                                    <div class="row">
                                        <div class="col-sm-4 mb-4 mb-sm-0">
                                            <label style="display: block; text-align: center" for="start_date">Event Start Date:</label>
                                            {{ form.start_date }}
                                        </div>
                                        <div class="col-sm-4 mb-4 mb-sm-0">
                                            <label style="display: block; text-align: center" for="end_date">Event End Date:</label>
                                            {{ form.end_date }}
                                        </div>
                                        <div class="col-sm-4 mb-4 mb-sm-0">
                                            <label style="display: block; text-align: center" for="subscribe_date">Last Subscribe Date:</label>
                                            {{ form.subscribe_date }}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6 mb-6 mb-sm-0">
                                    <div class="col-sm-12 mb-12 mb-sm-0">
                                        {{ form.description }}
                                    </div>
                                </div>
                            </div>
                            {% csrf_token %}
                            <br>
                            <div class="row">
                                <div class="col-sm-3 mb-3 mb-sm-0">
                                </div>
                                <div class="col-sm-3 mb-3 mb-sm-0">
                                    <input class="default btn btn-primary d-block btn-user w-100"  type="submit" value="Save" name="_save">
                                </div>
                                <div class="col-sm-3 mb-3 mb-sm-0">
                                    <input class="btn btn-primary d-block btn-user w-100" type="submit" value="Save and add another" name="_addanother">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/events/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Event Detail{% endblock title %}
{% block extra_css %}
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i&amp;display=swap">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Actor">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora">
<link rel="stylesheet" href="assets/fonts/fontawesome5-overrides.min.css">
<link rel="stylesheet" href="assets/css/article-nice.css">
{% endblock extra_css %}
{% block activeevents %} active {% endblock activeevents %}
{% block content %}
    <div class="container-fluid">
        <section class="article-dual-column">
            <div class="container">
                <div class="row">
                    <div class="col-md-10 offset-md-1">
                        <div class="intro">
                            <h1 class="text-center" id="inceput-1">{{event.title}}</h1>
                            <p class="text-center"> </p>
                            <div class="text-center">
                                <img class="img-fluid" src="{{event.photo.url}}" style="width: 670px;height: 434.388px;">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-10 col-lg-3 offset-md-1">
                        <div class="toc">
                            <p>More info:</p>
                            <ul>
                                <li>Country: {{event.country}}</li>
                                <li>City: {{event.city}}</li>
                                <li>Start: {{event.start_date|date:'d.m.Y'}}</li>
                                <li>End: {{event.end_date|date:'d.m.Y'}}</li>
                                <li>Subscribe to: {{event.subscribe_date|date:'d.m.Y'}}</li>
                                {% if event.attachment %}
                                    <li>Download info: <a href="{{ event.attachment.url }}" download>Download</a> </li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-10 col-lg-7 offset-md-1 offset-lg-0">
                        <div class="text">
                            <p style="font-family: Roboto, sans-serif;"><br>
                                <em>{{event.description}}</em>
                                <br>
                            </p>
                            <p style="font-family: Roboto, sans-serif;"><br>
                                <em>{{event.notes}}</em>
                                <br>
                            </p>
                            <h2 id="detaliitehnice-2">Subscriber:</h2>
                            <p style="font-family: Roboto, sans-serif;">
                                {% if subscriber %}
                                    {% for sub in subscriber %}
                                        {{sub.fullname}},
                                    {% endfor %}
                                {% else %}
                                        None
                                {% endif %}
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
{% endblock content %}

templates/events/list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Events{% endblock title %}
{% block activeevents %} active {% endblock activeevents %}
{% block content %}
<div class="container-fluid">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title text-uppercase mb-0">Events</h5>
        </div>
        <div class="table-responsive">
            <div id="sampleTable_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">
                <div class="row">
                    <div class="col-sm-12">
                        <table class="table table-hover table-bordered dataTable no-footer" id="sampleTable" role="grid" aria-describedby="sampleTable_info">
                            <thead>
                            <tr role="row">
                                <th style="width: 30px;">#</th>
                                <th scope="col" class="border-0 text-uppercase font-medium">Event Name</th>
                                <th scope="col" class="border-0 text-uppercase font-medium">Start Date</th>
                                <th scope="col" class="border-0 text-uppercase font-medium">End Date</th>
                                <th scope="col" class="border-0 text-uppercase font-medium">Subscribe Date</th>
                                {% if user.is_staff %}
                                    <th scope="col" class="border-0 text-uppercase font-medium">Manage</th>
                                {% endif %}
                            </tr>
                            </thead>
                            <tbody>
                            {% for event in object_list %}
                            <tr role="row" class="odd">
                                <td>{{ forloop.counter }}</td>
                                <td>{{ event.title }}</td>
                                <td>{{ event.start_date }}</td>
                                <td>{{ event.end_date }}</td>
                                <td>{{ event.subscribe_date }}</td>
                                {% if user.is_staff %}
                                <td>
                                    {% if user.is_staff %}
                                        {% if perms.auth.change_user %}
                                            <a href="{% url 'events:update' event.id %}">
                                                <button type="button" class="btn btn-outline-success btn-circle btn-lg btn-circle">
                                                    <i class="fa fa-edit"></i>
                                                </button>
                                            </a>
                                        {% endif %}
                                        {% if perms.auth.delete_user %}
                                        <a href="{% url 'events:delete' event.id %}">
                                            <button type="button" class="btn btn-outline-danger btn-circle btn-lg btn-circle ml-2">
                                                <i class="fa fa-trash"></i>
                                            </button>
                                        </a>
                                    {% endif %}
                                        <button type="button" class="btn btn-outline-primary btn-circle btn-lg btn-circle ml-2">
                                            <i class="fa fa-download"></i>
                                        </button>
                                    {% endif %}
                                </td>
                            {% endif %}
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="row">
        {% if perms.auth.add_user %}
        <a href="{% url 'events:create' %}">
            <button type="button" class="btn btn-outline-primary btn-circle btn-lg btn-circle">
                <i class="fa fa-plus"></i>
            </button>
        </a>
        {% endif %}
    </div>
    {% include "include/paginator_include.html" with page=page %}
</div>
{% endblock content %}